project_id = "lurrhrwggthyeicttsot"

[functions.handle-lead]
verify_jwt = false

[functions.log-traffic-event]
verify_jwt = false

[functions.mvt-optimize]
verify_jwt = false

[functions.test-telegram]
verify_jwt = false

[functions.generate-review-code]
verify_jwt = false

[functions.validate-review-code]
verify_jwt = false

[functions.submit-review]
verify_jwt = false

[functions._dev-genimg]
verify_jwt = false
